spring:
  devtools:
    add-properties: false
  redis:
    host: localhost
    password: password
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save

  datasource:
    url: jdbc:postgresql://localhost:5432/bada
    username: admin
    password: password

management:
  server:
    port: 8081

server:
  servlet:
    session:
      timeout: 72h