spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: trace